# Generated by Django 5.0.7 on 2024-07-23 11:30

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
